### ISSUE TITLE
支持在 iOS 环境下使用 devtools

### ISSUE THREAD

**Issue by andycall** [openkraken/devtools#4]
1. 需要构建一份 webkitGTK 2.26.1 所对应的 Safari 版本的 jsc 产物

**Comment by yuanyan** [comment]
需要先避免报错阻断链路

**Comment by andycall** [comment]
经测试，ios 版本的 JavaScriptCore.framework 无法安装在 iOS 设备上，在安装阶段系统会进行阻断。

对于报错处理已经兼容，并发布在最新的 0.2.0 版本上
